chore(localization): update strings in Registration page
accessibility-in-action/platform pull request #1059
Opened 2022-09-13 18:53 UTC by chosww

Explain what this PR does.

Update strings in the registration work flow.

### Prerequisites

If this PR changes PHP code or dependencies:

- [ ] I've run `composer format` and fixed any code formatting issues.
- [ ] I've run `composer analyze` and addressed any static analysis issues.
- [ ] I've run `php artisan test` and ensured that all tests pass.
- [ ] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

2022-09-15 23:48 UTC, greatislander requested changes

2022-09-15 23:48 UTC, greatislander commented on resources/lang/en/passwords.php
> +    'sent' => 'We have emailed you a password reset link for Accessibility Exchange. Please check your email.',
```suggestion
    'sent' => 'We have emailed you a password reset link for The Accessibility Exchange. Please check your email.',
```

2022-09-15 23:48 UTC, greatislander commented on resources/views/auth/register/steps/2.blade.php
> +                    'I am someone who has lived experience of being disabled or Deaf, or I am a family member or supporter or a person who is disabled or Deaf.',
```suggestion
                    'I am someone who has lived experience of being disabled or Deaf, or I am a family member or supporter of a person who is disabled or Deaf.',
```

2022-09-15 23:49 UTC, greatislander commented on resources/lang/en/passwords.php
> +    'sent' => 'We have emailed you a password reset link for Accessibility Exchange. Please check your email.',
```suggestion
    'sent' => 'We have emailed you a password reset link for The Accessibility Exchange. Please check your email.',
```

2022-09-15 23:50 UTC, greatislander approved these changes

2022-09-15 23:56 UTC, merged

2022-09-19 15:32 UTC, cherylhjli commented
Please refer to the colour coding on the latest wireframes for strings that are not matching the wires.

2022-09-19 15:36 UTC, greatislander commented
@chosww ☝🏻

2022-10-04 18:17 UTC, cherylhjli commented
https://staging.accessibilityexchange.ca/en/register?step=3
Email address 
Current: “This is also the email you use to log into this account. If you change this, you are also changing your log in email.”
Change to: “This is the email address you will use to sign in to The Accessibility Exchange.”

When registering as a CommOrg - selecting type of organization
- “Civil society organization”, not “broader civil society organizations”

When registering as a CommOrg - entering org name:
- the titles are: “Create new support organizations”, “create new representative organizations”, “create new broader civil society organizations” - drop the ’s’ at the end