feat: add ASL/LSQ placeholders and seeder
accessibility-in-action/platform pull request #1923
Opened 2023-10-05 18:57 UTC by jobara

### Prerequisites

If this PR changes PHP code or dependencies:

- [ ] I've run `composer format` and fixed any code formatting issues.
- [ ] I've run `composer analyze` and addressed any static analysis issues.
- [ ] I've run `php artisan test` and ensured that all tests pass.
- [ ] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

2023-10-11 18:03 UTC, chosww commented on resources/views/partials/join.blade.php
> +                @if ($withPricing ?? false) namespace="join-with_pricing"
Seems like updating namespace this way doesn't fully render the x-interpretation component, and that's why we were seeing the x-interpretation tags when we were looking at the test output yesterday. When I changed this condition to use ternary operator, I was able to see that the test output fully renders x-interpretation.

```
<x-interpretation name="{{ __('Join our accessibility community', [], 'en') }}"
                namespace="{{ isset($withPricing) ? 'join-with_pricing' : 'join' }}" />
```

2023-10-11 18:04 UTC, chosww commented on resources/views/partials/join.blade.php
> +                @if ($withPricing ?? false) namespace="join-with_pricing"
Also, the test in InterpretationTest is failing because we are missing 'class="text-center"' in the assertion. After adding that, the test passes.

2023-10-11 18:12 UTC, chosww requested changes
Thanks for the work @jobara, I left comment about the Interpretation test failure. Other than that, we need to update EngagementContractorsAndParticipantsTest, InvitationTest, and TranslationTest files' flash()->class status expectations from "toBe" to "toContain". Similar to that, IndividualTest's flash()->class status expectations need to be updated from "toBe" to "toContain".

2023-10-13 19:13 UTC, chosww commented
hey @jobara, I pushed the changes with the suggestions I made in this PR to my GH-1807; though, I am seeing weird test case failure around validating URLs on ProjectTest and RegulatedOrganizationTest. I am not sure if this is only happening locally, because other PRs from Ned with Laravel 10 upgrade passes all the tests from the CI. It would be great to see if tests from the CI passes once you merge my GH-1807.

2023-10-16 13:17 UTC, jobara commented
> hey @jobara, I pushed the changes with the suggestions I made in this PR to my [GH-1807](https://github.com/accessibility-exchange/platform/issues/1807); though, I am seeing weird test case failure around validating URLs on ProjectTest and RegulatedOrganizationTest. I am not sure if this is only happening locally, because other PRs from Ned with Laravel 10 upgrade passes all the tests from the CI. It would be great to see if tests from the CI passes once you merge my [GH-1807](https://github.com/accessibility-exchange/platform/issues/1807).

Thanks @chosww, I've merged in your branch to this PR. I changed the `toContain` to `toStartWith`.

2023-10-24 20:26 UTC, chosww commented
Thanks @jobara, the changes look good and the seeder is populating videos properly. One thing I noticed is that there's too much delay when I change items per pagination to 50 and change the pagination. Other options have little delays as well, but the delay caused by 50 items is very noticeable. We could change the maximum number of items to less items, but then there are so many videos, so there are pros and cons in my opinion.

2023-10-25 11:00 UTC, jobara commented
Just noticed that they per page drop down can be covered by the page links. If the screen isn't wide enough. This might need to go under a separate issue though unless the fix is quick. 

<img width="1210" alt="Screenshot 2023-10-25 at 6 59 01 AM" src="https://github.com/accessibility-exchange/platform/assets/556024/4d47c7c2-fb2d-4eda-92bf-dbb000a87ae2">

2023-10-25 11:02 UTC, jobara commented
> Thanks @jobara, the changes look good and the seeder is populating videos properly. One thing I noticed on the admin panel is that there's too much delay when I change items per pagination to 50 and change the pagination. Other options have little delays as well, but the delay caused by 50 items is very noticeable. We could change the maximum number of items to less items, but then there are so many videos, so there are pros and cons in my opinion.

I was trying this in Chrome this morning. I'm finding the page changes quickly but then there's a delay after. I wonder if it might be from the debug bar.

2023-10-25 11:18 UTC, jobara commented
> Just noticed that they per page drop down can be covered by the page links. If the screen isn't wide enough. This might need to go under a separate issue though unless the fix is quick.
> 
> <img alt="Screenshot 2023-10-25 at 6 59 01 AM" width="1210" src="https://user-images.githubusercontent.com/556024/277978859-4d47c7c2-fb2d-4eda-92bf-dbb000a87ae2.png">

This was fixed by Filament already in https://github.com/filamentphp/filament/pull/9162 I'm not sure when that will make it to a release though.

2023-10-25 11:49 UTC, jobara commented
> This was fixed by Filament already in [filamentphp/filament#9162](https://github.com/filamentphp/filament/pull/9162) It's included in [v3.0.80](https://github.com/filamentphp/filament/releases/tag/v3.0.80).

I've updated to the latest version of filament and related dependencies to get the fix for the page links.

2023-10-25 12:04 UTC, jobara commented
> > Thanks @jobara, the changes look good and the seeder is populating videos properly. One thing I noticed on the admin panel is that there's too much delay when I change items per pagination to 50 and change the pagination. Other options have little delays as well, but the delay caused by 50 items is very noticeable. We could change the maximum number of items to less items, but then there are so many videos, so there are pros and cons in my opinion.
> 
> I was trying this in Chrome this morning. I'm finding the page changes quickly but then there's a delay after. I wonder if it might be from the debug bar.

I set `APP_DEBUG=false` in my `.env` file and the filament page for interpretations worked much better. So I think it's probably related to the debug bar. Maybe we can check the dev site once this is deployed.

2023-10-26 15:40 UTC, jobara commented
Confirmed in matrix with @chosww and @greatislander about merging this PR as is. If there are any issues or changes needed, new issues will be filed for them.

See: [Accessibility Exchange Matrix conversation](https://matrix.to/#/!QRQCoXAWrIjYQVYaai:matrix.org/$IuotsLdj3QVwW48549zozxlsxkCg5aSWEwrVoKcmIpI?via=matrix.org)

2023-10-26 15:40 UTC, merged