fix: model lsq translations don't fallback to fr (resolves #2014, #2026)
accessibility-in-action/platform pull request #2027
Opened 2023-11-29 19:32 UTC by jobara

Resolves #2014 
Resolves #2026

- Renames `get_written_language_for_signed_language` to `to_written_language`
- Makes use of the `missingKeyCallback` to fallback lsq to fr
- Removes HasMultimodalTranslations trait, as this is handled by the `missingKeyCallback`
- Adds tests for the use of `missingKeyCallback`

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

2023-11-30 13:08 UTC, jobara commented
@greatislander in fixing the failing test I realized that I may have removed some functionality, but I'm also not sure how that part was supposed to work or if it was actually functional on the site. I wonder if you could weigh in. Basically I removed the language bits from the controllers. It looks like you could use that to pass in a query parameter to have an individual or organization public page rendered in an alternative language if one was provided. However, I don't see how a user could have specified that query parameter. Am I understanding this correctly? Have I missed something? Is this still needed?

2023-11-30 22:20 UTC, jobara commented
> @greatislander in fixing the failing test I realized that I may have removed some functionality, but I'm also not sure how that part was supposed to work or if it was actually functional on the site. I wonder if you could weigh in. Basically I removed the language bits from the controllers. It looks like you could use that to pass in a query parameter to have an individual or organization public page rendered in an alternative language if one was provided. However, I don't see how a user could have specified that query parameter. Am I understanding this correctly? Have I missed something? Is this still needed?

I spoke with @greatislander about this. The `$language` set from the query parameter is to allow those pages to be shown in different languages, if they've been added for them by the user/org. This for example would allow an organization to localize their public page in many languages even though the site only supports a couple. Will need to bring that functionality back. While the written language supports from HasMultimodalTranslations isn't required any more, the rough in for the ASL/LSQ upload options is still requested to remain, in case we implement those features in the future.

2023-11-30 22:23 UTC, jobara commented
While reviewing this, @greatislander found two other bugs ( #2029, #2028 ). If possible these should be addressed alongside this one.

2023-12-08 14:24 UTC, greatislander requested changes

2023-12-08 14:24 UTC, greatislander commented on app/helpers.php
> +use Illuminate\Support\Facades\Route as FacadesRoute;
I'd call this `RouteFacade` instead.

2023-12-12 12:47 UTC, greatislander approved these changes

2023-12-12 12:57 UTC, merged