Infrastructure local environment update nix
accessibility-in-action/platform pull request #2429
Opened 2024-12-10 18:42 UTC by marvinroman

Adds a new local development environment that with the help of [Nix](https://nixos.org/) which can easily setup the local development environment and make sure all necessary dependencies are available.

Also sets up helpful environment specific command aliases for interacting with `docker-compose` and `kubectl`.

2024-12-11 12:36 UTC, jobara reviewed
Should this replace the local docker development environment?

2024-12-11 14:46 UTC, marvinroman commented
> Should this replace the local docker development environment?

It adds to that environment it doesn't replace it.  
It makes setting up that environment a single step of running `nix-shell`.  
It does have the requirement of Nix package manager which allows the creation of the development environment with all the necessary packages and aliases.

2024-12-12 18:03 UTC, jobara reviewed
I installed nix an ran `nix-shell` but this is the error I'm getting.

```log
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/wy0baqdmchbz603wvcl8fj64daanm5n7-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'
         at /nix/store/wy0baqdmchbz603wvcl8fj64daanm5n7-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:383:7:
          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Package ‘rootlesskit-2.3.1’ in /nix/store/wy0baqdmchbz603wvcl8fj64daanm5n7-nixpkgs/nixpkgs/pkgs/by-name/ro/rootlesskit/package.nix:23 is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
```

2024-12-16 08:55 UTC, marvinroman commented
There is an issue with [rootlesskit for mac](https://github.com/rootless-containers/rootlesskit/issues/201) so it cannot be installed on Macos without workarounds. I made it so that it only installs on linux systems.

I altered the instruction to reflect this change.

2025-01-06 19:39 UTC, jobara requested changes

2025-01-06 19:39 UTC, jobara commented on README.md
> +| `dstart`* | short for `pkill dockerd` kills the dockerd process |
is this supposed to be `dstop`?

2025-01-06 19:40 UTC, jobara commented
@marvinroman I keep getting "Cannot connect to the Docker daemon at unix:///docker.sock. Is the docker daemon running?" error when trying to run docker commands in nix-shell. Any idea what might be wrong?

2025-01-07 16:27 UTC, marvinroman commented on README.md
> +| `dstart`* | short for `pkill dockerd` kills the dockerd process |
Yes that should be fixed.

2025-01-07 16:30 UTC, marvinroman commented
> @marvinroman I keep getting "Cannot connect to the Docker daemon at unix:///docker.sock. Is the docker daemon running?" error when trying to run docker commands in nix-shell. Any idea what might be wrong?

I think it's likely because we were updating `DOCKER_HOST` path to work with `dockerd-rootless`. I have made sure that is only updated for Linux environments.
You will have to have Docker installed and running before running the commands.

2025-01-20 17:05 UTC, jobara commented
In general this seems to be working but I get this warning after running nix-shell and calling `dcbp`:

```
WARN[0000] current commit information was not captured by the build  error="failed to read current commit information with git rev-parse --is-inside-work-tree"
```

2025-01-21 09:19 UTC, marvinroman commented
> In general this seems to be working but I get this warning after running nix-shell and calling `dcbp`:
> 
> ```
> WARN[0000] current commit information was not captured by the build  error="failed to read current commit information with git rev-parse --is-inside-work-tree"
> ```

I am not able to duplicate or find much online about this error. Can you try this [thread](https://stackoverflow.com/questions/76264761/warning-buildx-failed-to-read-current-commit-information-with-git-rev-parse) unfortunately there isn't much information provided to say what might be causing it.

2025-01-21 18:48 UTC, jobara approved these changes

2025-01-21 18:48 UTC, merged