chore(localization): update strings in registration page
accessibility-in-action/platform pull request #942
Opened 2022-08-24 19:12 UTC by chosww

See #792 for details.

2022-08-25 12:32 UTC, greatislander requested changes

2022-08-25 12:32 UTC, greatislander commented on resources/views/dashboard.blade.php
> -        <p>{{ $user->name }}@if($memberable), {{ $memberable->name }}@endif</p>
The `@if` tag here no longer does anything— it needs to be wrapped around the `{{ $memberable->name }}` (this accounts for one of the test failures as there are some instances where a user is not a member of an organization).

2022-08-25 12:40 UTC, greatislander requested changes

2022-08-25 12:40 UTC, greatislander commented on resources/views/auth/register/steps/4.blade.php
> +            {{ __('For your security, please make sure your password has:') }}
the `<x-hearth-hint>` component doesn't support multiple block-level elements (in this case, a paragraph and an unordered list). It's probably best to not use the hint component and wrap this all in a `<div>` like this:

```html
<div class="field__hint" id="password-hint">
...
</div>
``

2022-08-25 12:40 UTC, greatislander commented on resources/views/organizations/show-role-selection.blade.php
> +            <x-hearth-hint for="roles">{{ __('Please tell us what your organization would like to do here. You must pick at least one of these roles. You can always change this later.') }} <a target=
"Learn more about these roles" is not properly wrapped in `__('')` and thus won't be picked up for translation. Please make sure it is processed like line 11 above.

2022-08-25 13:42 UTC, greatislander requested changes

2022-08-25 13:42 UTC, greatislander commented on resources/views/organizations/show-role-selection.blade.php
> +            <x-hearth-hint for="roles">{{ __('Please tell us what your organization would like to do here. You must pick at least one of these roles. You can always change this later.') }} <a target=
I think you are missing a period at the end of this sentence.

2022-08-25 13:42 UTC, greatislander commented on resources/views/auth/register/steps/4.blade.php
>              {{ __('For your security, please make sure your password has:') }}
Wrap this in a `<p>` tag as we aren't processing it with Markdown as is normally the case in the hint component.

2022-08-25 13:56 UTC, greatislander approved these changes

2022-08-25 14:01 UTC, merged

2022-08-25 15:55 UTC, cherylhjli commented
@chosww what page did you update? Sorry the original figma link doesn't seem to work anymore!

2022-08-29 14:47 UTC, cherylhjli commented
@chosww the copy under the "learn more" component on this page isn't there: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A4237