fix: roles-and-permissions (resolves #848)
accessibility-in-action/platform pull request #974
Opened 2022-08-30 18:54 UTC by chosww

Add a new policy in UserPolicy to give access to /roles-and-permissions page for users belongs to an organization.

This will resolve the issue #848.

2022-08-30 19:07 UTC, chosww commented
I noticed two test cases are failing from the dev branch, and they are:

Session has unexpected errors: 
  
  [
      "The accessibility_and_inclusion_links.0.url is not a valid URL."
  ]
  Failed asserting that true is false.

  at tests/Feature/RegulatedOrganizationTest.php:111
  
  -----------------------------------------------------
  
  Session has unexpected errors: 
  
  [
      "The team_trainings.0.trainer_url is not a valid URL."
  ]
  Failed asserting that true is false.

  at tests/Feature/ProjectTest.php:306

2022-08-31 00:45 UTC, greatislander requested changes
This looks good to me, @chosww — please add some tests to cover the new behaviour for the roles and permissions page itself as well as the invitations page and it'll be good to merge.

2022-08-31 00:45 UTC, greatislander commented on tests/Feature/UserSettingsTest.php
> +test('users belong to an organization can invite new members to their organization or regulated organization', function () {
```suggestion
test('users belonging to an organization or regulated organization can invite new members to their organization or regulated organization', function () {
```

2022-08-31 00:45 UTC, greatislander commented on tests/Feature/UserSettingsTest.php
Please add tests to "users can edit roles and permissions" test to check that:

- [ ] Organization users with an organization can access the page
- [ ] Regulated organization users without a regulated organization cannot access the page
- [ ] Organization users without an organization cannot access the page

2022-08-31 00:48 UTC, greatislander commented
> I noticed two test cases are failing from the dev branch, and they are:
> 
> Session has unexpected errors:
> 
> [ "The accessibility_and_inclusion_links.0.url is not a valid URL." ] Failed asserting that true is false.
> 
> at tests/Feature/RegulatedOrganizationTest.php:111
> 
> Session has unexpected errors:
> 
> [ "The team_trainings.0.trainer_url is not a valid URL." ] Failed asserting that true is false.
> 
> at tests/Feature/ProjectTest.php:306

@chosww Can you paste in the contents of lines 104-112 of RegulatedOrganizationTest.php and lines 293-307 of ProjectTest.php for me? I think I know what's happening but I'm still puzzled as to why I'm not seeing those failures.

2022-08-31 13:13 UTC, chosww commented
> > I noticed two test cases are failing from the dev branch, and they are:
> > Session has unexpected errors:
> > [ "The accessibility_and_inclusion_links.0.url is not a valid URL." ] Failed asserting that true is false.
> > at tests/Feature/RegulatedOrganizationTest.php:111
> > Session has unexpected errors:
> > [ "The team_trainings.0.trainer_url is not a valid URL." ] Failed asserting that true is false.
> > at tests/Feature/ProjectTest.php:306
> 
> @chosww Can you paste in the contents of lines 104-112 of RegulatedOrganizationTest.php and lines 293-307 of ProjectTest.php for me? I think I know what's happening but I'm still puzzled as to why I'm not seeing those failures.

RegulatedOrganizationTest lines 104-112:

```
$response = $this->actingAs($user)->put(localized_route('regulated-organizations.update', $regulatedOrganization), [
    'name' => ['en' => $regulatedOrganization->name],
    'service_areas' => ['NU'],
    'accessibility_and_inclusion_links' => [['title' => 'Accessibility Statement', 'url' => 'https://example.com/accessibility']],
    'social_links' => ['facebook' => ''],
    'publish' => 'Publish',
]);
$response->assertSessionHasNoErrors();
$response->assertRedirect(localized_route('regulated-organizations.show', $regulatedOrganization));
```

ProjectTest line 293-307:
```
$response = $this->actingAs($user)->put(localized_route('projects.update-team', $project), [
'team_count' => '42',
'team_languages' => ['en'],
'team_trainings' => [
    ['name' => 'Example Training', 'date' => '2022-04-01', 'trainer_name' => 'Acme Training Co.', 'trainer_url' => 'example.com'],
],
'contact_person_email' => 'me@here.com',
'contact_person_name' => 'Jonny Appleseed',
'preferred_contact_method' => 'email',
'contact_person_response_time' => ['en' => 'ASAP'],
'save_and_previous' => __('Save and previous'),
]);

$response->assertSessionHasNoErrors();
$response->assertRedirect(localized_route('projects.edit', ['project' => $project, 'step' => 1]));
```

2022-08-31 14:35 UTC, greatislander requested changes

2022-08-31 14:35 UTC, greatislander commented on tests/Feature/UserSettingsTest.php
> +test('users belong to an organization can invite new members to their organization or regulated organization', function () {
```suggestion
test('users belonging to an organization or regulated organization can invite new members to their organization or regulated organization', function () {
```

2022-08-31 14:42 UTC, greatislander approved these changes

2022-08-31 14:42 UTC, merged